FROM registry.access.redhat.com/ubi10/nginx-126:10.0

COPY ./nginx.conf /etc/nginx/nginx.conf
COPY ./index.html /opt/app-root/src/index.html

EXPOSE 8080

LABEL org.opencontainers.image.source https://github.com/hardomx/argo-guestbook

CMD [ "nginx", "-g", "daemon off;" ]
